nelmio_api_doc:
    documentation:
        info:
            title: Test
            description: Mayflower test
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc|doc.json$) # Accepts routes under /api except /api/doc
